package com.anuragcharitabletrust;

import java.io.IOException;
import java.io.PrintWriter;

import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;


public class LandingPageServlet extends HttpServlet{
	private static final long serialVersionUID = 1L;
	private int counter=0;
	public void doGet(HttpServletRequest req,HttpServletResponse res) throws IOException {
		counter++;
		PrintWriter out=res.getWriter();
		out.print("<!DOCTYPE html>\r\n"
				+ "<html lang=\"en\">\r\n"
				+ "\r\n"
				+ "<head>\r\n"
				+ "    <meta charset=\"UTF-8\">\r\n"
				+ "    <title>Anurag Charitable Trust</title>\r\n"
				+ "    <style>\r\n"
				+ "        /* Global styles */\r\n"
				+ "        body {\r\n"
				+ "            margin: 0;\r\n"
				+ "            font-family: Arial, sans-serif;\r\n"
				+ "            font-size: 16px;\r\n"
				+ "        }\r\n"
				+ "\r\n"
				+ "        /* Header styles */\r\n"
				+ "        header {\r\n"
				+ "            background-color: #ffa318;\r\n"
				+ "            color: #FFFFFF;\r\n"
				+ "            padding: 10px;\r\n"
				+ "            display: flex;\r\n"
				+ "            justify-content: space-between;\r\n"
				+ "            align-items: center;\r\n"
				+ "        }\r\n"
				+ "\r\n"
				+ "        #logo {\r\n"
				+ "            font-size: 24px;\r\n"
				+ "            font-weight: bold;\r\n"
				+ "            color: inherit;\r\n"
				+ "            text-decoration: none;\r\n"
				+ "        }\r\n"
				+ "\r\n"
				+ "        #menu {\r\n"
				+ "            display: flex;\r\n"
				+ "            gap: 20px;\r\n"
				+ "        }\r\n"
				+ "\r\n"
				+ "        #menu a {\r\n"
				+ "            color: #FFFFFF;\r\n"
				+ "            text-decoration: none;\r\n"
				+ "            padding: 10px;\r\n"
				+ "            border-radius: 5px;\r\n"
				+ "        }\r\n"
				+ "\r\n"
				+ "        #menu a:hover {\r\n"
				+ "            background-color: #FFFFFF;\r\n"
				+ "            color: #0047AB;\r\n"
				+ "        }\r\n"
				+ "\r\n"
				+ "        /* Main styles */\r\n"
				+ "        main {\r\n"
				+ "            padding: 20px;\r\n"
				+ "        }\r\n"
				+ "\r\n"
				+ "        h1 {\r\n"
				+ "            font-size: 36px;\r\n"
				+ "            margin-top: 0;\r\n"
				+ "        }\r\n"
				+ "\r\n"
				+ "        p {\r\n"
				+ "            line-height: 1.5;\r\n"
				+ "        }\r\n"
				+ "\r\n"
				+ "        .causes {\r\n"
				+ "            display: flex;\r\n"
				+ "            gap: 20px;\r\n"
				+ "            margin-top: 20px;\r\n"
				+ "        }\r\n"
				+ "\r\n"
				+ "        .cause {\r\n"
				+ "            flex: 1;\r\n"
				+ "            background-color: #F2F2F2;\r\n"
				+ "            padding: 20px;\r\n"
				+ "            border-radius: 5px;\r\n"
				+ "        }\r\n"
				+ "\r\n"
				+ "        .cause h2 {\r\n"
				+ "            font-size: 24px;\r\n"
				+ "            margin-top: 0;\r\n"
				+ "        }\r\n"
				+ "\r\n"
				+ "        .cause p {\r\n"
				+ "            margin-top: 10px;\r\n"
				+ "        }\r\n"
				+ "\r\n"
				+ "        /* Counter styles */\r\n"
				+ "        footer {\r\n"
				+ "            background-color: #0047AB;\r\n"
				+ "            color: #FFFFFF;\r\n"
				+ "            padding: 10px;\r\n"
				+ "            text-align: center;\r\n"
				+ "        }\r\n"
				+ "    </style>\r\n"
				+ "</head>\r\n"
				+ "\r\n"
				+ "<body>\r\n"
				+ "    <header>\r\n"
				+ "        <a href=\"\\ngo1\" id=\"logo\"><div id=\"logo\">Anurag Charitable Trust</div></a>\r\n"
				+ "        <nav id=\"menu\">\r\n"
				+ "            <a href=\"\ngo1\\ourwork.html\">Our Work</a>\r\n"
				+ "            <a href=\"\\ngo1\\getinvolved\">Get Involved</a>\r\n"
				+ "            <a href=\"#\">Gallery</a>\r\n"
				+ "            <a href=\"#\">About Us</a>\r\n"
				+ "            <a href=\"#\">Contact Us</a>\r\n"
				+ "        </nav>\r\n"
				+ "    </header>\r\n"
				+ "    <main>\r\n"
				+ "        <h1>Our Causes</h1>\r\n"
				+ "        <p>We support the following causes:</p>\r\n"
				+ "        <div class=\"causes\">\r\n"
				+ "            <div class=\"cause\">\r\n"
				+ "                <h2>Animal Welfare</h2>\r\n"
				+ "                <p>Animal welfare is essential for protecting the rights and wellbeing of animals and promoting their humane treatment. ACT raises awareness about animal welfare issues, promotes responsible pet ownership, and advocates for animal-friendly policies and laws.</p>\r\n"
				+ "            </div>\r\n"
				+ "            <div class=\"cause\">\r\n"
				+ "                <h2>Menstrual Awareness</h2>\r\n"
				+ "                <p>Menstrual awareness is vital for promoting menstrual hygiene, providing access to menstrual products, and breaking down social and cultural barriers to menstruation. ACT is playing a key role in advocating for menstrual hygiene and breaking down social and cultural barriers to menstruation.</p>\r\n"
				+ "            </div>\r\n"
				+ "            <div class=\"cause\">\r\n"
				+ "                <h2>Education of Orphans</h2>\r\n"
				+ "                <p>The education of orphans is crucial for promoting their rights to education and breaking the cycle of poverty. ACT attempts to provide access to quality education and advocate for policies and programs that support the educational needs of orphans, contributing to the development of their communities and society as a whole.\r\n"
				+ "            </div>\r\n"
				+ "        </div>\r\n"
				+ "    </main>\r\n"
				+ "    <footer>\r\n"
				+ "        This website has been visited "+counter+" times.\r\n"
				+ "    </footer>\r\n"
				+ "</body>\r\n"
				+ "\r\n"
				+ "</html>");
	}
}
